package cn.whaley.moretv.member.api.service.member.impl;

import cn.whaley.moretv.member.api.service.member.MemberUserAuthorityService;
import cn.whaley.moretv.member.base.constant.CacheKeyConstant;
import cn.whaley.moretv.member.base.mapper.GenericMapper;
import cn.whaley.moretv.member.base.service.impl.GenericServiceImpl;
import cn.whaley.moretv.member.mapper.member.MemberUserAuthorityMapper;
import cn.whaley.moretv.member.model.member.MemberUserAuthority;
import com.alibaba.fastjson.JSON;
import com.google.common.collect.Lists;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.redis.core.HashOperations;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.CollectionUtils;
import org.springframework.util.StringUtils;

import java.util.List;
import java.util.Map;


/**
* ServiceImpl: MemberUserAuthorityServiceImpl
* Mapper : MemberUserAuthorityMapper
* Model  : MemberUserAuthority
*
* This ServiceImpl generated by MyBatis Generator Extend at 2017-03-30 17:05:25
*/
@Service
@Transactional
public class MemberUserAuthorityServiceImpl extends GenericServiceImpl<MemberUserAuthority, Integer> implements MemberUserAuthorityService {

    @Autowired
    private MemberUserAuthorityMapper memberUserAuthorityMapper;

    @Autowired
    private RedisTemplate<String, String> redisTemplate;

    @Override
    public List<MemberUserAuthority> getMemberUserAuthority(Integer accountId) {
        List<MemberUserAuthority> list = Lists.newArrayList();
        HashOperations<String, String, String> opsHash = redisTemplate.opsForHash();

        String key = String.format(CacheKeyConstant.REDIS_KEY_MEMBER_AUTHORITY, accountId.toString());
        Map<String, String> map = opsHash.entries(key);
        if (CollectionUtils.isEmpty(map)) {
            return list;
        }

        for (Map.Entry<String, String> entry : map.entrySet()) {
            MemberUserAuthority authority = JSON.parseObject(entry.getValue(), MemberUserAuthority.class);
            list.add(authority);
        }
        return list;
    }

    @Override
    public GenericMapper<MemberUserAuthority, Integer> getGenericMapper() {
        return memberUserAuthorityMapper;
    }

}