package cn.whaley.moretv.member.api.service;

import cn.whaley.moretv.member.base.service.GenericService;
import cn.whaley.moretv.member.model.order.DeliveredOrder;

/**
* Service: DeliveredOrderService
* Mapper : DeliveredOrderMapper
* Model  : DeliveredOrder
*
* This Service generated by MyBatis Generator Extend at 2017-04-27 15:33:08
*/
public interface DeliveredOrderService extends GenericService<DeliveredOrder, Integer> {
}