package cn.whaley.moretv.member.api.service.cp;

import cn.whaley.moretv.member.base.dto.request.BaseRequest;
import cn.whaley.moretv.member.base.dto.response.ResultResponse;
import cn.whaley.moretv.member.service.cp.BaseCpAccountService;

/**
* Service: CpAccountService
* Mapper : CpAccountMapper
* Model  : CpAccount
*
* This Service generated by MyBatis Generator Extend at 2017-04-13 15:43:39
*/
public interface CpAccountService extends BaseCpAccountService {

    ResultResponse getCpAccountInfo(BaseRequest baseRequest);

}