package cn.whaley.moretv.member.sync.service.member;

import java.util.Map;

import cn.whaley.moretv.member.base.service.GenericService;
import cn.whaley.moretv.member.model.member.MemberProgramRelation;
import cn.whaley.moretv.member.sync.dto.goods.ProductDto;

/**
* Service: MemberProgramRelationService
* Mapper : MemberProgramRelationMapper
* Model  : MemberProgramRelation
*
* This Service generated by MyBatis Generator Extend at 2017-03-03 11:41:48
*/
public interface MemberProgramRelationService extends GenericService<MemberProgramRelation, Integer> {

    void sync(ProductDto productDto);

    Map<String, String> resetRedis(String programCode);
}