package cn.whaley.moretv.member.api.service.impl;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import cn.whaley.moretv.member.api.service.DeliveredOrderService;
import cn.whaley.moretv.member.base.service.impl.GenericServiceImpl;
import cn.whaley.moretv.member.mapper.order.DeliveredOrderMapper;
import cn.whaley.moretv.member.model.order.DeliveredOrder;

/**
* ServiceImpl: DeliveredOrderServiceImpl
* Mapper : DeliveredOrderMapper
* Model  : DeliveredOrder
*
* This ServiceImpl generated by MyBatis Generator Extend at 2017-04-27 15:33:08
*/
@Service
@Transactional
public class DeliveredOrderServiceImpl extends GenericServiceImpl<DeliveredOrder, Integer, DeliveredOrderMapper> implements DeliveredOrderService {
    @Autowired
    private DeliveredOrderMapper deliveredOrderMapper;

    @Override
    public DeliveredOrderMapper getGenericMapper() {
        return deliveredOrderMapper;
    }
}