package cn.whaley.moretv.member.model.cp;

import cn.whaley.moretv.member.base.model.BaseModel;
import java.io.Serializable;
import java.util.Date;

/**
* Model: CpOrderItem
* Table: cp_order_item
* Alias: cpori
*
* This Model generated by MyBatis Generator Extend.
*/
public class CpOrderItem extends BaseModel<Integer> implements Serializable {
    /**
     * CP订单号
     * cp_order_code
     */
    private String cpOrderCode;

    /**
     * CP产品包
     * cp_product
     */
    private String cpProduct;

    /**
     * 有效时长
     * duration_month
     */
    private Integer durationMonth;

    /**
     * 有效时长(天)
     * duration_day
     */
    private Integer durationDay;

    /**
     * 单价
     * price
     */
    private Integer price;

    /**
     * 总价
     * total_price
     */
    private Integer totalPrice;

    /**
     * 
     * cp_order_status
     */
    private Integer cpOrderStatus;

    /**
     * 创建时间
     * create_time
     */
    private Date createTime;

    /**
     * 更新时间
     * update_time
     */
    private Date updateTime;

    private static final long serialVersionUID = 1L;

    /**
     * CP订单号
     * cp_order_code
     */
    public String getCpOrderCode() {
        return cpOrderCode;
    }

    /**
     * CP订单号
     * cp_order_code
     *
     * @param cpOrderCode CP订单号
     */
    public void setCpOrderCode(String cpOrderCode) {
        this.cpOrderCode = cpOrderCode;
    }

    /**
     * CP产品包
     * cp_product
     */
    public String getCpProduct() {
        return cpProduct;
    }

    /**
     * CP产品包
     * cp_product
     *
     * @param cpProduct CP产品包
     */
    public void setCpProduct(String cpProduct) {
        this.cpProduct = cpProduct;
    }

    /**
     * 有效时长
     * duration_month
     */
    public Integer getDurationMonth() {
        return durationMonth;
    }

    /**
     * 有效时长
     * duration_month
     *
     * @param durationMonth 有效时长
     */
    public void setDurationMonth(Integer durationMonth) {
        this.durationMonth = durationMonth;
    }

    /**
     * 有效时长(天)
     * duration_day
     */
    public Integer getDurationDay() {
        return durationDay;
    }

    /**
     * 有效时长(天)
     * duration_day
     *
     * @param durationDay 有效时长(天)
     */
    public void setDurationDay(Integer durationDay) {
        this.durationDay = durationDay;
    }

    /**
     * 单价
     * price
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * 单价
     * price
     *
     * @param price 单价
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * 总价
     * total_price
     */
    public Integer getTotalPrice() {
        return totalPrice;
    }

    /**
     * 总价
     * total_price
     *
     * @param totalPrice 总价
     */
    public void setTotalPrice(Integer totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * 
     * cp_order_status
     */
    public Integer getCpOrderStatus() {
        return cpOrderStatus;
    }

    /**
     * 
     * cp_order_status
     *
     * @param cpOrderStatus 
     */
    public void setCpOrderStatus(Integer cpOrderStatus) {
        this.cpOrderStatus = cpOrderStatus;
    }

    /**
     * 创建时间
     * create_time
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 创建时间
     * create_time
     *
     * @param createTime 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 更新时间
     * update_time
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 更新时间
     * update_time
     *
     * @param updateTime 更新时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cpOrderCode=").append(cpOrderCode);
        sb.append(", cpProduct=").append(cpProduct);
        sb.append(", durationMonth=").append(durationMonth);
        sb.append(", durationDay=").append(durationDay);
        sb.append(", price=").append(price);
        sb.append(", totalPrice=").append(totalPrice);
        sb.append(", cpOrderStatus=").append(cpOrderStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CpOrderItem other = (CpOrderItem) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}