package cn.whaley.moretv.member.model.cp;

import cn.whaley.moretv.member.base.model.BaseModel;
import java.io.Serializable;
import java.util.Date;

/**
* Model: CpOrder
* Table: cp_order
* Alias: cpord
*
* This Model generated by MyBatis Generator Extend.
*/
public class CpOrder extends BaseModel<Integer> implements Serializable {
    /**
     * CP订单号
     * cp_order_code
     */
    private String cpOrderCode;

    /**
     * 业务订单号
     * business_order_code
     */
    private String businessOrderCode;

    /**
     * CP账号
     * cp_account
     */
    private String cpAccount;

    /**
     * 订单状态
     * cp_order_status
     */
    private Integer cpOrderStatus;

    /**
     * 创建时间
     * create_time
     */
    private Date createTime;

    /**
     * 更新时间
     * update_time
     */
    private Date updateTime;

    private static final long serialVersionUID = 1L;

    /**
     * CP订单号
     * cp_order_code
     */
    public String getCpOrderCode() {
        return cpOrderCode;
    }

    /**
     * CP订单号
     * cp_order_code
     *
     * @param cpOrderCode CP订单号
     */
    public void setCpOrderCode(String cpOrderCode) {
        this.cpOrderCode = cpOrderCode;
    }

    /**
     * 业务订单号
     * business_order_code
     */
    public String getBusinessOrderCode() {
        return businessOrderCode;
    }

    /**
     * 业务订单号
     * business_order_code
     *
     * @param businessOrderCode 业务订单号
     */
    public void setBusinessOrderCode(String businessOrderCode) {
        this.businessOrderCode = businessOrderCode;
    }

    /**
     * CP账号
     * cp_account
     */
    public String getCpAccount() {
        return cpAccount;
    }

    /**
     * CP账号
     * cp_account
     *
     * @param cpAccount CP账号
     */
    public void setCpAccount(String cpAccount) {
        this.cpAccount = cpAccount;
    }

    /**
     * 订单状态
     * cp_order_status
     */
    public Integer getCpOrderStatus() {
        return cpOrderStatus;
    }

    /**
     * 订单状态
     * cp_order_status
     *
     * @param cpOrderStatus 订单状态
     */
    public void setCpOrderStatus(Integer cpOrderStatus) {
        this.cpOrderStatus = cpOrderStatus;
    }

    /**
     * 创建时间
     * create_time
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 创建时间
     * create_time
     *
     * @param createTime 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 更新时间
     * update_time
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 更新时间
     * update_time
     *
     * @param updateTime 更新时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cpOrderCode=").append(cpOrderCode);
        sb.append(", businessOrderCode=").append(businessOrderCode);
        sb.append(", cpAccount=").append(cpAccount);
        sb.append(", cpOrderStatus=").append(cpOrderStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CpOrder other = (CpOrder) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}