package cn.whaley.moretv.member.mapper.goods;

import cn.whaley.moretv.member.base.mapper.GenericMapper;
import cn.whaley.moretv.member.model.goods.Goods;

/**
* Mapper: GoodsMapper
* Model : Goods
* Table : goods
*
* This Mapper generated by MyBatis Generator Extend at 2017-02-20 19:19:11
*/
public interface GoodsMapper extends GenericMapper<Goods, Integer> {
}