package cn.whaley.moretv.member.mapper.goods;

import cn.whaley.moretv.member.base.mapper.GenericMapper;
import cn.whaley.moretv.member.model.goods.GoodsSku;

import java.util.List;

import org.apache.ibatis.annotations.Select;

/**
* Mapper: GoodsSkuMapper
* Model : GoodsSku
* Table : goods_sku
*
* This Mapper generated by MyBatis Generator Extend at 2017-02-20 19:19:11
*/
public interface GoodsSkuMapper extends GenericMapper<GoodsSku, Integer> {

    @Select("select count(1) from goods_sku where id = #{id}")
    int existGoodsSkuById(Integer id);

    int insertWithId(GoodsSku goodsSku);

    List<GoodsSku> selectByGoodsCode(String goodsCode);

}