package cn.whaley.moretv.member.mapper.goods;

import cn.whaley.moretv.member.base.mapper.GenericMapper;
import cn.whaley.moretv.member.model.goods.GoodsSpu;
import org.apache.ibatis.annotations.Select;

/**
* Mapper: GoodsSpuMapper
* Model : GoodsSpu
* Table : goods_spu
*
* This Mapper generated by MyBatis Generator Extend at 2017-02-20 19:19:11
*/
public interface GoodsSpuMapper extends GenericMapper<GoodsSpu, Integer> {

    @Select("select count(1) from goods_spu where id = #{id}")
    int existGoodsSpuById(Integer id);

    int insertWithId(GoodsSpu goodsSpu);
}