package cn.whaley.moretv.member.mapper.goods;

import cn.whaley.moretv.member.base.mapper.GenericMapper;
import cn.whaley.moretv.member.model.goods.GoodsSku;

/**
* Mapper: GoodsSkuMapper
* Model : GoodsSku
* Table : goods_sku
*
* This Mapper generated by MyBatis Generator Extend at 2017-02-20 19:19:11
*/
public interface GoodsSkuMapper extends GenericMapper<GoodsSku, Integer> {
}