package cn.whaley.moretv.member.mapper.goods;

import java.util.List;

import cn.whaley.moretv.member.base.mapper.GenericMapper;
import cn.whaley.moretv.member.model.goods.MemberProgramRelation;

/**
* Mapper: MemberProgramRelationMapper
* Model : MemberProgramRelation
* Table : member_program_relation
*
* This Mapper generated by MyBatis Generator Extend at 2017-03-03 11:41:48
*/
public interface MemberProgramRelationMapper extends GenericMapper<MemberProgramRelation, Integer> {

    List<MemberProgramRelation> listByProgramCode(String productCode);
}