package cn.whaley.moretv.member.mapper.goods;

import java.util.List;

import org.apache.ibatis.annotations.Select;

import cn.whaley.moretv.member.base.mapper.GenericMapper;
import cn.whaley.moretv.member.model.goods.MemberPackageRelation;

/**
* Mapper: MemberPackageRelationMapper
* Model : MemberPackageRelation
* Table : member_package_relation
*
* This Mapper generated by MyBatis Generator Extend at 2017-03-02 17:06:04
*/
public interface MemberPackageRelationMapper extends GenericMapper<MemberPackageRelation, Integer> {

    @Select("select * from member_package_relation where member_code = #{memberCode}")
    List<MemberPackageRelation> listByMemberCode(String memberCode);
}