package cn.whaley.moretv.member.mapper.goods;

import cn.whaley.moretv.member.base.mapper.GenericMapper;
import cn.whaley.moretv.member.model.goods.MemberProgram;

/**
* Mapper: MemberProgramMapper
* Model : MemberProgram
* Table : member_program
*
* This Mapper generated by MyBatis Generator Extend at 2017-03-02 17:06:04
*/
public interface MemberProgramMapper extends GenericMapper<MemberProgram, Integer> {
}