package cn.whaley.moretv.member.api.service.goods;

import cn.whaley.moretv.member.base.res.ResultResponse;
import cn.whaley.moretv.member.service.goods.BaseGoodsService;

/**
* Service: GoodsService
* Mapper : GoodsMapper
* Model  : Goods
*
* This Service generated by MyBatis Generator Extend at 2017-03-21 14:37:17
*/
public interface GoodsService extends BaseGoodsService {

    /**
     * 根据goodsTag(即商品模型编码)获取对应的商品
     * 需判断用户是否是会员，是会员返回续费类别商品，不是会员返回购买。
     * 还需判断用户是否是首次购买，是首次购买，返回首次购买和普通商品，不是则返回非首次购买和普通商品。
     * @param accountId
     * @param goodsTag
     * @return
     */
    ResultResponse getGoodsByTag(Integer accountId, String goodsTag);
}