package cn.whaley.moretv.member.api.service.goods;

import cn.whaley.moretv.member.base.res.ResultResponse;
import cn.whaley.moretv.member.base.service.GenericService;
import cn.whaley.moretv.member.model.goods.GoodsSpu;

/**
* Service: GoodsSpuService
* Mapper : GoodsSpuMapper
* Model  : GoodsSpu
*
* This Service generated by MyBatis Generator Extend at 2017-03-21 14:37:17
*/
public interface GoodsSpuService extends GenericService<GoodsSpu, Integer> {

    /**
     * 获取所有独立商品模型
     * @return
     */
    ResultResponse getGoodsSpuList();

}