package cn.whaley.moretv.member.notify.service.cp;

import cn.whaley.moretv.member.base.service.GenericService;
import cn.whaley.moretv.member.model.cp.CpAccount;

/**
* Service: CpAccountService
* Mapper : CpAccountMapper
* Model  : CpAccount
*
* This Service generated by MyBatis Generator Extend at 2017-04-13 15:43:39
*/
public interface CpAccountService extends GenericService<CpAccount, Integer> {
}