package cn.whaley.moretv.member.sync.service.goods.impl;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.redis.core.HashOperations;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.alibaba.fastjson.JSON;

import cn.whaley.moretv.member.base.constant.ApiCodeEnum;
import cn.whaley.moretv.member.base.constant.CacheKeyConstant;
import cn.whaley.moretv.member.base.constant.GlobalEnum;
import cn.whaley.moretv.member.base.dto.response.ResultResponse;
import cn.whaley.moretv.member.base.exception.SystemException;
import cn.whaley.moretv.member.model.goods.GoodsSpu;
import cn.whaley.moretv.member.service.goods.impl.BaseGoodsSpuServiceImpl;
import cn.whaley.moretv.member.sync.service.goods.GoodsSpuService;
import cn.whaley.moretv.member.sync.util.RedisResetResponseUtil;

/**
* ServiceImpl: GoodsSpuServiceImpl
* Mapper : GoodsSpuMapper
* Model  : GoodsSpu
*
* This ServiceImpl generated by MyBatis Generator Extend at 2017-02-20 20:07:22
*/
@Service
@Transactional
public class GoodsSpuServiceImpl extends BaseGoodsSpuServiceImpl implements GoodsSpuService {

    private static final Logger logger = LoggerFactory.getLogger(GoodsSpuServiceImpl.class);

    @Autowired
    private RedisTemplate redisTemplate;
    
    @Override
    public ResultResponse syncGoodsSpu(GoodsSpu goodsSpu) {
        HashOperations<String, String, String> opsHash = redisTemplate.opsForHash();

        String status = goodsSpu.getGoodsStatus();

        if (GlobalEnum.StatusText.OFFSHEIF.getCode().equals(status)) {
            offsheifGoodsSpu(goodsSpu, opsHash);
        } else if (GlobalEnum.StatusText.PUBLISHED.getCode().equals(status)){
            publishGoodsSpu(goodsSpu, opsHash);
        } else {
            throw new SystemException(ApiCodeEnum.API_DATA_GOODS_STATUS_ERR);
        }

        return ResultResponse.success();
    }

    private void offsheifGoodsSpu(GoodsSpu goodsSpu, HashOperations<String, String, String> opsHash) {
        opsHash.delete(CacheKeyConstant.REDIS_KEY_GOODS_SPU, goodsSpu.getGoodsBaseCode());
        logger.info("syncGoodsSpu: 删除商品模型缓存, goodsBaseCode:{}", goodsSpu.getGoodsBaseCode());

        GoodsSpu spu = new GoodsSpu();
        spu.setId(goodsSpu.getId());
        spu.setGoodsStatus(GlobalEnum.StatusText.OFFSHEIF.getCode());
        spu.setUpdateTime(goodsSpu.getUpdateTime());
        int line = goodsSpuMapper.updateByPrimaryKeySelective(spu);
        if (line > 0) {
            logger.info("syncGoodsSpu: 修改商品模型状态为未发布, goodsBaseCode:{}", goodsSpu.getGoodsBaseCode());
        }
    }

    private void publishGoodsSpu(GoodsSpu goodsSpu, HashOperations<String, String, String> opsHash) {
        //独立商品模型才存入redis
        if (GlobalEnum.CompositedType.SINGLE.getCode() == goodsSpu.getCompositedType().intValue()) {
            String value = JSON.toJSONString(goodsSpu);
            opsHash.put(CacheKeyConstant.REDIS_KEY_GOODS_SPU, goodsSpu.getGoodsBaseCode(), value);
            logger.info("syncGoodsSpu: 更新商品模型缓存, goodsBaseCode:{}", goodsSpu.getGoodsBaseCode());
        }

        int count = goodsSpuMapper.existGoodsSpuById(goodsSpu.getId());
        if (count > 0) {
            goodsSpuMapper.updateByPrimaryKeySelective(goodsSpu);
            logger.info("syncGoodsSpu: 更新商品模型数据, goodsBaseCode:{}", goodsSpu.getGoodsBaseCode());
        } else {
            goodsSpuMapper.insertWithId(goodsSpu);
            logger.info("syncGoodsSpu: 同步商品模型数据, goodsBaseCode:{}", goodsSpu.getGoodsBaseCode());
        }
    }

    @Override
    public Map<String, Object> resetRedis() {
        HashOperations<String, String, String> opsHash = redisTemplate.opsForHash();
        List<String> addList = new ArrayList<>();
        List<String> deleteList = new ArrayList<>();
        
        Set<String> goodsSpuKeys = opsHash.keys(CacheKeyConstant.REDIS_KEY_GOODS_SPU);
        for(String key : goodsSpuKeys){
            opsHash.delete(CacheKeyConstant.REDIS_KEY_GOODS_SPU, key);
            deleteList.add(key);
            logger.info("resetGoodsSpu: 清除商品模型缓存, goodsBaseCode:{}", key);
        }
        
        List<GoodsSpu> goodsSpuList = goodsSpuMapper.selectAll();
        for(GoodsSpu goodsSpu : goodsSpuList){
            if (GlobalEnum.StatusText.PUBLISHED.getCode().equals(goodsSpu.getGoodsStatus()) &&
                    GlobalEnum.CompositedType.SINGLE.getCode() == goodsSpu.getCompositedType().intValue()) {
                String value = JSON.toJSONString(goodsSpu);
                opsHash.put(CacheKeyConstant.REDIS_KEY_GOODS_SPU, goodsSpu.getGoodsBaseCode(), value);
                addList.add( goodsSpu.getGoodsBaseCode());
                logger.info("resetGoodsSpu: 重新插入商品模型缓存, goodsBaseCode:{}", goodsSpu.getGoodsBaseCode());
            }
        }
        return RedisResetResponseUtil.getResetRedisMap(addList, deleteList);
    }

}