package cn.whaley.moretv.member.sync.service.goods.impl;

import cn.whaley.moretv.member.base.mapper.GenericMapper;
import cn.whaley.moretv.member.base.service.impl.GenericServiceImpl;
import cn.whaley.moretv.member.mapper.goods.GoodsSkuMapper;
import cn.whaley.moretv.member.model.goods.GoodsSku;
import cn.whaley.moretv.member.sync.service.goods.GoodsSkuService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
* ServiceImpl: GoodsSkuServiceImpl
* Mapper : GoodsSkuMapper
* Model  : GoodsSku
*
* This ServiceImpl generated by MyBatis Generator Extend at 2017-02-20 20:07:22
*/
@Service
@Transactional
public class GoodsSkuServiceImpl extends GenericServiceImpl<GoodsSku, Integer> implements GoodsSkuService {
    @Autowired
    private GoodsSkuMapper goodsSkuMapper;

    @Override
    public GenericMapper<GoodsSku, Integer> getGenericMapper() {
        return goodsSkuMapper;
    }
}