package cn.whaley.moretv.member.mapper.order;

import cn.whaley.moretv.member.base.mapper.GenericMapper;
import cn.whaley.moretv.member.model.order.DeliveredOrder;

/**
* Mapper: DeliveredOrderMapper
* Model : DeliveredOrder
* Table : delivered_order
*
* This Mapper generated by MyBatis Generator Extend at 2017-04-27 16:30:50
*/
public interface DeliveredOrderMapper extends GenericMapper<DeliveredOrder, Integer> {
}