package cn.whaley.moretv.member.mapper.order;

import java.util.List;

import org.apache.ibatis.annotations.Select;

import cn.whaley.moretv.member.base.mapper.GenericMapper;
import cn.whaley.moretv.member.model.order.Order;
import cn.whaley.moretv.member.model.order.OrderItem;

/**
* Mapper: OrderItemMapper
* Model : OrderItem
* Table : business_order_item
*
* This Mapper generated by MyBatis Generator Extend at 2017-03-31 15:00:02
*/
public interface OrderItemMapper extends GenericMapper<OrderItem, Integer> {
	
	@Select("select * from business_order_item where orderNo = #{orderNo}")
	List<OrderItem> getByOrderNo(String orderNo);
}