package cn.whaley.moretv.member.mapper.order;

import java.util.List;

import cn.whaley.moretv.member.base.mapper.GenericMapper;
import cn.whaley.moretv.member.model.order.Order;

/**
* Mapper: OrderMapper
* Model : Order
* Table : business_order
*
* This Mapper generated by MyBatis Generator Extend at 2017-03-31 15:00:02
*/
public interface OrderMapper extends GenericMapper<Order, Integer> {

    List<Order> listByAccountId(String accoundId);

    Order getByOrderCode(String orderCode);
}