package cn.whaley.moretv.member.api.service.goods.impl;

import cn.whaley.moretv.member.api.dto.goods.GoodsDto;
import cn.whaley.moretv.member.api.dto.goods.GoodsResponse;
import cn.whaley.moretv.member.api.service.goods.GoodsService;
import cn.whaley.moretv.member.api.service.member.MemberService;
import cn.whaley.moretv.member.api.util.ResponseHandler;
import cn.whaley.moretv.member.base.constant.ApiCodeEnum;
import cn.whaley.moretv.member.base.constant.CacheKeyConstant;
import cn.whaley.moretv.member.base.constant.GlobalEnum;
import cn.whaley.moretv.member.base.mapper.GenericMapper;
import cn.whaley.moretv.member.base.dto.response.ResultResponse;
import cn.whaley.moretv.member.mapper.goods.GoodsMapper;
import cn.whaley.moretv.member.model.goods.Goods;
import cn.whaley.moretv.member.service.goods.impl.BaseGoodsServiceImpl;
import com.alibaba.fastjson.JSON;
import com.google.common.collect.Lists;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.redis.core.HashOperations;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.CollectionUtils;

import java.util.List;
import java.util.Map;

/**
* ServiceImpl: GoodsServiceImpl
* Mapper : GoodsMapper
* Model  : Goods
*
* This ServiceImpl generated by MyBatis Generator Extend at 2017-03-21 14:37:17
*/
@Service
@Transactional
public class GoodsServiceImpl extends BaseGoodsServiceImpl implements GoodsService {

    private static final Logger logger = LoggerFactory.getLogger(GoodsServiceImpl.class);

    @Autowired
    private GoodsMapper goodsMapper;

    @Autowired
    private RedisTemplate redisTemplate;

    @Autowired
    private MemberService memberService;

    @Override
    public ResultResponse getGoodsByTag(Integer accountId, String goodsTag) {
        HashOperations<String, String, String> opsHash = redisTemplate.opsForHash();
        List<GoodsResponse> goodsList = Lists.newArrayList();
        Integer normalGoods = GlobalEnum.GoodsType.NORMAL_GOODS.getValue();

        boolean isMember = memberService.accountIsMember(accountId);

        Integer goodsType = isMember ? GlobalEnum.GoodsType.RENEWAL_GOODS.getValue() : normalGoods;

        logger.info("get_goods_by_tag : accountId:{}, goodsTag:{}, isMember:{}, goodsType:{}",
                accountId, goodsTag, isMember, goodsType);

        String key = String.format(CacheKeyConstant.REDIS_KEY_GOODS, goodsType);
        Map<String, String> map = opsHash.entries(key);
        if (CollectionUtils.isEmpty(map)) {
            return ResultResponse.define(ApiCodeEnum.API_DATA_NOT_EXIST);
        }

        boolean hasPurchaseOrder = true;
        if (normalGoods.equals(goodsType)) {
            //TODO hasPurchaseOrder = baseOrderService.hasPurchaseOrder(accountId);
        }

        logger.info("get_goods_by_tag :  accountId:{}, goodsSize:{}, hasPurchaseOrder:{}",
                accountId, map.size(), hasPurchaseOrder);

        for (Map.Entry<String, String> entry : map.entrySet()) {
            GoodsDto goodsDto = JSON.parseObject(entry.getValue(), GoodsDto.class);
            Integer goodsClass = goodsDto.getGoodsClass();

            if (hasPurchaseOrder && GlobalEnum.GoodsClass.FIRST_GOODS.getCode() == goodsClass.intValue()) {
                continue;
            } else if (!hasPurchaseOrder && GlobalEnum.GoodsClass.NOT_FIRST_GOODS.getCode() == goodsClass.intValue()){
                continue;
            }
            GoodsResponse response = ResponseHandler.converGoods(goodsDto);
            goodsList.add(response);
        }

        return ResultResponse.success(goodsList);
    }

    @Override
    public GenericMapper<Goods, Integer> getGenericMapper() {
        return goodsMapper;
    }

}