package cn.whaley.moretv.member.api.service.goods.impl;

import cn.whaley.moretv.member.api.dto.response.GoodsSpuResponse;
import cn.whaley.moretv.member.api.service.goods.GoodsSpuService;
import cn.whaley.moretv.member.api.util.ResponseHandler;
import cn.whaley.moretv.member.base.constant.ApiCodeEnum;
import cn.whaley.moretv.member.base.constant.CacheKeyConstant;
import cn.whaley.moretv.member.base.constant.GlobalEnum;
import cn.whaley.moretv.member.base.mapper.GenericMapper;
import cn.whaley.moretv.member.base.res.ResultResponse;
import cn.whaley.moretv.member.base.service.impl.GenericServiceImpl;
import cn.whaley.moretv.member.mapper.goods.GoodsSpuMapper;
import cn.whaley.moretv.member.model.goods.GoodsSpu;
import com.alibaba.fastjson.JSON;
import com.google.common.collect.Lists;
import com.google.common.collect.Maps;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.redis.core.HashOperations;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.CollectionUtils;

import java.util.List;
import java.util.Map;

/**
* ServiceImpl: GoodsSpuServiceImpl
* Mapper : GoodsSpuMapper
* Model  : GoodsSpu
*
* This ServiceImpl generated by MyBatis Generator Extend at 2017-03-21 14:37:17
*/
@Service
@Transactional
public class GoodsSpuServiceImpl extends GenericServiceImpl<GoodsSpu, Integer> implements GoodsSpuService {

    @Autowired
    private GoodsSpuMapper goodsSpuMapper;

    @Autowired
    private RedisTemplate redisTemplate;

    @Override
    public ResultResponse getGoodsSpuList() {
        HashOperations<String, String, String> opsHash = redisTemplate.opsForHash();
        List<GoodsSpuResponse> goodsSpuList = Lists.newArrayList();

        Map<String, String> map = opsHash.entries(CacheKeyConstant.REDIS_KEY_GOODS_SPU);
        if (CollectionUtils.isEmpty(map)) {
            return ResultResponse.define(ApiCodeEnum.API_DATA_NOT_EXIST);
        }

        for (Map.Entry<String, String> entry : map.entrySet()) {
            GoodsSpu goodsSpu = JSON.parseObject(entry.getValue(), GoodsSpu.class);
            GoodsSpuResponse response = ResponseHandler.converGoodsSpu(goodsSpu);
            goodsSpuList.add(response);
        }

        return ResultResponse.success(goodsSpuList);
    }

    @Override
    public GenericMapper<GoodsSpu, Integer> getGenericMapper() {
        return goodsSpuMapper;
    }

}