package cn.whaley.moretv.member.api.service.order;

import cn.whaley.moretv.member.base.service.GenericService;
import cn.whaley.moretv.member.model.order.OrderItem;

/**
* Service: OrderItemService
* Mapper : OrderItemMapper
* Model  : OrderItem
*
* This Service generated by MyBatis Generator Extend at 2017-04-27 15:33:08
*/
public interface OrderItemService extends GenericService<OrderItem, Integer> {
}