package cn.whaley.moretv.member.api.service.cp.impl;

import cn.whaley.moretv.member.api.dto.member.MemberCpResponse;
import cn.whaley.moretv.member.api.service.cp.CpAccountService;
import cn.whaley.moretv.member.base.dto.request.BaseRequest;
import cn.whaley.moretv.member.base.dto.response.ResultResponse;
import cn.whaley.moretv.member.model.cp.CpAccount;
import cn.whaley.moretv.member.service.cp.impl.BaseCpAccountServiceImpl;
import com.google.common.collect.Lists;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
* ServiceImpl: CpAccountServiceImpl
* Mapper : CpAccountMapper
* Model  : CpAccount
*
* This ServiceImpl generated by MyBatis Generator Extend at 2017-04-13 15:43:39
*/
@Service
@Transactional
public class CpAccountServiceImpl extends BaseCpAccountServiceImpl implements CpAccountService {

    @Override
    public ResultResponse getCpAccountInfo(BaseRequest baseRequest) {
        List<MemberCpResponse> memberCpResponseList = Lists.newArrayList();
        List<CpAccount> cpAccountList = cpAccountMapper.getCpAccountList(baseRequest.getAccountId());

        for (CpAccount account : cpAccountList) {
            memberCpResponseList.add(new MemberCpResponse(
                    account.getCpAccount(), account.getCpToken(), account.getCpSource()));
        }

        return ResultResponse.success(memberCpResponseList);
    }
}