package cn.whaley.moretv.member.model.member;

import cn.whaley.moretv.member.base.model.BaseModel;
import java.io.Serializable;
import java.util.Date;

/**
* Model: MemberUserCp
* Table: member_user_cp
* Alias: muc
*
* This Model generated by MyBatis Generator Extend.
*/
public class MemberUserCp extends BaseModel<Integer> implements Serializable {
    /**
     * cp用户名
     * cp_username
     */
    private String cpUsername;

    /**
     * cp令牌
     * cp_token
     */
    private String cpToken;

    /**
     * cp来源
     * cp_source
     */
    private String cpSource;

    /**
     * 电视猫用户名
     * account_id
     */
    private Integer accountId;

    /**
     * delete：删除，valid：正常
     * status
     */
    private String status;

    /**
     * 创建时间
     * create_time
     */
    private Date createTime;

    /**
     * 更新时间
     * update_time
     */
    private Date updateTime;

    private static final long serialVersionUID = 1L;

    /**
     * cp用户名
     * cp_username
     */
    public String getCpUsername() {
        return cpUsername;
    }

    /**
     * cp用户名
     * cp_username
     *
     * @param cpUsername cp用户名
     */
    public void setCpUsername(String cpUsername) {
        this.cpUsername = cpUsername;
    }

    /**
     * cp令牌
     * cp_token
     */
    public String getCpToken() {
        return cpToken;
    }

    /**
     * cp令牌
     * cp_token
     *
     * @param cpToken cp令牌
     */
    public void setCpToken(String cpToken) {
        this.cpToken = cpToken;
    }

    /**
     * cp来源
     * cp_source
     */
    public String getCpSource() {
        return cpSource;
    }

    /**
     * cp来源
     * cp_source
     *
     * @param cpSource cp来源
     */
    public void setCpSource(String cpSource) {
        this.cpSource = cpSource;
    }

    /**
     * 电视猫用户名
     * account_id
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * 电视猫用户名
     * account_id
     *
     * @param accountId 电视猫用户名
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * delete：删除，valid：正常
     * status
     */
    public String getStatus() {
        return status;
    }

    /**
     * delete：删除，valid：正常
     * status
     *
     * @param status delete：删除，valid：正常
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * 创建时间
     * create_time
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 创建时间
     * create_time
     *
     * @param createTime 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 更新时间
     * update_time
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 更新时间
     * update_time
     *
     * @param updateTime 更新时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cpUsername=").append(cpUsername);
        sb.append(", cpToken=").append(cpToken);
        sb.append(", cpSource=").append(cpSource);
        sb.append(", accountId=").append(accountId);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MemberUserCp other = (MemberUserCp) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}