package cn.whaley.moretv.member.mapper.cp;

import cn.whaley.moretv.member.base.mapper.GenericMapper;
import cn.whaley.moretv.member.model.cp.CpAccount;

/**
* Mapper: CpAccountMapper
* Model : CpAccount
* Table : cp_account
*
* This Mapper generated by MyBatis Generator Extend at 2017-04-13 15:43:39
*/
public interface CpAccountMapper extends GenericMapper<CpAccount, Integer> {
}