package cn.whaley.moretv.member.mapper.cp;

import cn.whaley.moretv.member.base.mapper.GenericMapper;
import cn.whaley.moretv.member.model.cp.CpAccount;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
* Mapper: CpAccountMapper
* Model : CpAccount
* Table : cp_account
*
* This Mapper generated by MyBatis Generator Extend at 2017-04-13 15:43:39
*/
public interface CpAccountMapper extends GenericMapper<CpAccount, Integer> {

    /**
     * 通过accountId和cpSource查询CP账号
     * @param accountId
     * @param cpSource
     * @return
     */
    CpAccount getCpAccount(@Param("accountId") Integer accountId, @Param("cpSource") String cpSource);

    /**
     * 查询accountId对应的所有CP账号
     * @param accountId
     * @return
     */
    List<CpAccount> getCpAccountList(Integer accountId);

}