package cn.whaley.moretv.member.mapper.cp;

import cn.whaley.moretv.member.base.mapper.GenericMapper;
import cn.whaley.moretv.member.model.cp.CpOrderItem;

/**
* Mapper: CpOrderItemMapper
* Model : CpOrderItem
* Table : cp_order_item
*
* This Mapper generated by MyBatis Generator Extend at 2017-04-13 15:43:39
*/
public interface CpOrderItemMapper extends GenericMapper<CpOrderItem, Integer> {
}