package cn.whaley.moretv.member.sync.service.member.impl;

import cn.whaley.moretv.member.base.mapper.GenericMapper;
import cn.whaley.moretv.member.base.service.impl.GenericServiceImpl;
import cn.whaley.moretv.member.mapper.member.MemberMapper;
import cn.whaley.moretv.member.model.member.Member;
import cn.whaley.moretv.member.sync.service.member.MemberService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
* ServiceImpl: MemberServiceImpl
* Mapper : MemberMapper
* Model  : Member
*
* This ServiceImpl generated by MyBatis Generator Extend at 2017-03-29 14:25:15
*/
@Service
@Transactional
public class MemberServiceImpl extends GenericServiceImpl<Member, Integer> implements MemberService {
    @Autowired
    private MemberMapper memberMapper;

    @Override
    public GenericMapper<Member, Integer> getGenericMapper() {
        return memberMapper;
    }
}