package cn.whaley.moretv.member.sync.service.member.impl;

import cn.whaley.moretv.member.base.mapper.GenericMapper;
import cn.whaley.moretv.member.base.service.impl.GenericServiceImpl;
import cn.whaley.moretv.member.mapper.member.MemberProgramRelationMapper;
import cn.whaley.moretv.member.model.member.MemberProgramRelation;
import cn.whaley.moretv.member.sync.service.member.MemberProgramRelationService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
* ServiceImpl: MemberProgramRelationServiceImpl
* Mapper : MemberProgramRelationMapper
* Model  : MemberProgramRelation
*
* This ServiceImpl generated by MyBatis Generator Extend at 2017-03-29 14:25:15
*/
@Service
@Transactional
public class MemberProgramRelationServiceImpl extends GenericServiceImpl<MemberProgramRelation, Integer> implements MemberProgramRelationService {
    @Autowired
    private MemberProgramRelationMapper memberProgramRelationMapper;

    @Override
    public GenericMapper<MemberProgramRelation, Integer> getGenericMapper() {
        return memberProgramRelationMapper;
    }
}