package cn.whaley.moretv.member.sync.service.goods.impl;

import cn.whaley.moretv.member.base.mapper.GenericMapper;
import cn.whaley.moretv.member.base.service.impl.GenericServiceImpl;
import cn.whaley.moretv.member.mapper.goods.GoodsSpuMapper;
import cn.whaley.moretv.member.model.goods.GoodsSpu;
import cn.whaley.moretv.member.sync.service.goods.GoodsSpuService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
* ServiceImpl: GoodsSpuServiceImpl
* Mapper : GoodsSpuMapper
* Model  : GoodsSpu
*
* This ServiceImpl generated by MyBatis Generator Extend at 2017-02-20 20:07:22
*/
@Service
@Transactional
public class GoodsSpuServiceImpl extends GenericServiceImpl<GoodsSpu, Integer> implements GoodsSpuService {
    @Autowired
    private GoodsSpuMapper goodsSpuMapper;

    @Override
    public GenericMapper<GoodsSpu, Integer> getGenericMapper() {
        return goodsSpuMapper;
    }
}