package cn.whaley.moretv.member.sync.service.goods.impl;

import cn.whaley.moretv.member.base.mapper.GenericMapper;
import cn.whaley.moretv.member.base.service.impl.GenericServiceImpl;
import cn.whaley.moretv.member.mapper.goods.GoodsMapper;
import cn.whaley.moretv.member.model.goods.Goods;
import cn.whaley.moretv.member.sync.service.goods.GoodsService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
* ServiceImpl: GoodsServiceImpl
* Mapper : GoodsMapper
* Model  : Goods
*
* This ServiceImpl generated by MyBatis Generator Extend at 2017-02-20 20:07:22
*/
@Service
@Transactional
public class GoodsServiceImpl extends GenericServiceImpl<Goods, Integer> implements GoodsService {
    @Autowired
    private GoodsMapper goodsMapper;

    @Override
    public GenericMapper<Goods, Integer> getGenericMapper() {
        return goodsMapper;
    }
}