package cn.whaley.moretv.member.sync.service.goods.impl;

import cn.whaley.moretv.member.base.mapper.GenericMapper;
import cn.whaley.moretv.member.base.service.impl.GenericServiceImpl;
import cn.whaley.moretv.member.mapper.goods.MemberProgramMapper;
import cn.whaley.moretv.member.model.goods.MemberProgram;
import cn.whaley.moretv.member.sync.service.goods.MemberProgramService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
* ServiceImpl: MemberProgramServiceImpl
* Mapper : MemberProgramMapper
* Model  : MemberProgram
*
* This ServiceImpl generated by MyBatis Generator Extend at 2017-03-02 17:06:04
*/
@Service
@Transactional
public class MemberProgramServiceImpl extends GenericServiceImpl<MemberProgram, Integer> implements MemberProgramService {
    @Autowired
    private MemberProgramMapper memberProgramMapper;

    @Override
    public GenericMapper<MemberProgram, Integer> getGenericMapper() {
        return memberProgramMapper;
    }
}