package cn.whaley.moretv.member.sync.service.goods.impl;

import cn.whaley.moretv.member.base.mapper.GenericMapper;
import cn.whaley.moretv.member.base.service.impl.GenericServiceImpl;
import cn.whaley.moretv.member.mapper.goods.MemberPackageRelationMapper;
import cn.whaley.moretv.member.model.goods.MemberPackageRelation;
import cn.whaley.moretv.member.sync.service.goods.MemberPackageRelationService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
* ServiceImpl: MemberPackageRelationServiceImpl
* Mapper : MemberPackageRelationMapper
* Model  : MemberPackageRelation
*
* This ServiceImpl generated by MyBatis Generator Extend at 2017-03-02 17:06:04
*/
@Service
@Transactional
public class MemberPackageRelationServiceImpl extends GenericServiceImpl<MemberPackageRelation, Integer> implements MemberPackageRelationService {
    @Autowired
    private MemberPackageRelationMapper memberPackageRelationMapper;

    @Override
    public GenericMapper<MemberPackageRelation, Integer> getGenericMapper() {
        return memberPackageRelationMapper;
    }
}