package cn.whaley.moretv.member.notify.service.cp.impl;

import cn.whaley.moretv.member.base.constant.GlobalConstant;
import cn.whaley.moretv.member.base.constant.GlobalEnum;
import cn.whaley.moretv.member.model.cp.CpAccount;
import cn.whaley.moretv.member.notify.service.cp.CpAccountService;
import cn.whaley.moretv.member.service.cp.impl.BaseCpAccountServiceImpl;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Date;

/**
* ServiceImpl: CpAccountServiceImpl
* Mapper : CpAccountMapper
* Model  : CpAccount
*
* This ServiceImpl generated by MyBatis Generator Extend at 2017-04-13 15:43:39
*/
@Service
@Transactional
public class CpAccountServiceImpl extends BaseCpAccountServiceImpl implements CpAccountService {

    @Override
    public CpAccount getCpAccount(Integer accountId, String cpSource) {
        return cpAccountMapper.getCpAccount(accountId, cpSource);
    }

    @Override
    public CpAccount createCpAccount(String cpAccountId, String cpToken, Integer accountId, Date date) {
        CpAccount account = new CpAccount();
        account.setCpAccount(cpAccountId);
        account.setCpToken(cpToken);
        account.setAccountId(accountId);
        account.setCpSource(GlobalConstant.CP_TENCENT);
        account.setStatus(GlobalEnum.StatusText.VALID.getCode());
        account.setCreateTime(date);
        cpAccountMapper.insertSelective(account);
        return account;
    }
}