package cn.whaley.moretv.member.notify.service.cp.impl;

import cn.whaley.moretv.member.base.constant.GlobalConstant;
import cn.whaley.moretv.member.base.constant.GlobalEnum;
import cn.whaley.moretv.member.base.service.impl.GenericServiceImpl;
import cn.whaley.moretv.member.mapper.cp.CpAccountMapper;
import cn.whaley.moretv.member.model.cp.CpAccount;
import cn.whaley.moretv.member.notify.service.cp.CpAccountService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Date;

/**
* ServiceImpl: CpAccountServiceImpl
* Mapper : CpAccountMapper
* Model  : CpAccount
*
* This ServiceImpl generated by MyBatis Generator Extend at 2017-04-13 15:43:39
*/
@Service
@Transactional
public class CpAccountServiceImpl extends GenericServiceImpl<CpAccount, Integer, CpAccountMapper> implements CpAccountService {

    @Autowired
    private CpAccountMapper cpAccountMapper;

    @Override
    public CpAccountMapper getGenericMapper() {
        return cpAccountMapper;
    }


    @Override
    public CpAccount getCpAccount(Integer accountId, String cpSource) {
        return cpAccountMapper.getCpAccount(accountId, cpSource);
    }

    @Override
    public String createCpAccount(String cpAccountId, String cpToken, Integer accountId, Date date) {
        CpAccount account = new CpAccount();
        account.setCpAccount(cpAccountId);
        account.setCpToken(cpToken);
        account.setAccountId(accountId);
        account.setCpSource(GlobalConstant.CP_TENCENT);
        account.setStatus(GlobalEnum.StatusText.VALID.getCode());
        account.setCreateTime(date);
        cpAccountMapper.insertSelective(account);
        return account.getCpAccount();
    }
}