package cn.whaley.moretv.member.notify.service.cp.impl;

import cn.whaley.moretv.member.base.service.impl.GenericServiceImpl;
import cn.whaley.moretv.member.mapper.cp.CpAccountMapper;
import cn.whaley.moretv.member.model.cp.CpAccount;
import cn.whaley.moretv.member.notify.service.cp.CpAccountService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
* ServiceImpl: CpAccountServiceImpl
* Mapper : CpAccountMapper
* Model  : CpAccount
*
* This ServiceImpl generated by MyBatis Generator Extend at 2017-04-13 15:43:39
*/
@Service
@Transactional
public class CpAccountServiceImpl extends GenericServiceImpl<CpAccount, Integer, CpAccountMapper> implements CpAccountService {

    @Autowired
    private CpAccountMapper cpAccountMapper;

    @Override
    public CpAccountMapper getGenericMapper() {
        return cpAccountMapper;
    }
}