package cn.whaley.moretv.member.sync.service.goods;

import cn.whaley.moretv.member.base.service.GenericService;
import cn.whaley.moretv.member.model.goods.GoodsSku;

/**
* Service: GoodsSkuService
* Mapper : GoodsSkuMapper
* Model  : GoodsSku
*
* This Service generated by MyBatis Generator Extend at 2017-02-20 19:19:11
*/
public interface GoodsSkuService extends GenericService<GoodsSku, Integer> {
}