package cn.whaley.moretv.member.mapper.member;

import cn.whaley.moretv.member.base.mapper.GenericMapper;
import cn.whaley.moretv.member.model.member.MemberProgramRelation;

import java.util.List;

/**
* Mapper: MemberProgramRelationMapper
* Model : MemberProgramRelation
* Table : member_program_relation
*
* This Mapper generated by MyBatis Generator Extend at 2017-03-29 14:25:15
*/
public interface MemberProgramRelationMapper extends GenericMapper<MemberProgramRelation, Integer> {

    List<MemberProgramRelation> listByProgramCode(String productCode);

}