package cn.whaley.moretv.member.mapper.member;

import cn.whaley.moretv.member.base.mapper.GenericMapper;
import cn.whaley.moretv.member.model.member.MemberUserAuthority;

/**
* Mapper: MemberUserAuthorityMapper
* Model : MemberUserAuthority
* Table : member_user_authority
*
* This Mapper generated by MyBatis Generator Extend at 2017-03-30 17:05:25
*/
public interface MemberUserAuthorityMapper extends GenericMapper<MemberUserAuthority, Integer> {
}