package cn.whaley.moretv.member.mapper.member;

import org.apache.ibatis.annotations.Select;

import cn.whaley.moretv.member.base.mapper.GenericMapper;
import cn.whaley.moretv.member.model.member.Member;
import cn.whaley.moretv.member.model.member.MemberUserAuthority;

/**
* Mapper: MemberUserAuthorityMapper
* Model : MemberUserAuthority
* Table : member_user_authority
*
* This Mapper generated by MyBatis Generator Extend at 2017-03-30 17:05:25
*/
public interface MemberUserAuthorityMapper extends GenericMapper<MemberUserAuthority, Integer> {
	
	@Select("select * from member_user_authority where accountId = #{accountId} and memberCode = #{memberCode} and status = 1 ")
	MemberUserAuthority selectByAccountIdAndMemberCode(Integer accountId,String memberCode);
}