package cn.whaley.moretv.member.mapper.member;

import cn.whaley.moretv.member.base.mapper.GenericMapper;
import cn.whaley.moretv.member.model.member.Member;

/**
* Mapper: MemberMapper
* Model : Member
* Table : member
*
* This Mapper generated by MyBatis Generator Extend at 2017-03-29 14:25:15
*/
public interface MemberMapper extends GenericMapper<Member, Integer> {

    Member selectByCode(String code);

}