package cn.whaley.moretv.member.mapper.member;

import cn.whaley.moretv.member.base.mapper.GenericMapper;
import cn.whaley.moretv.member.model.member.MemberPackageRelation;

import java.util.List;

/**
* Mapper: MemberPackageRelationMapper
* Model : MemberPackageRelation
* Table : member_package_relation
*
* This Mapper generated by MyBatis Generator Extend at 2017-03-29 14:25:15
*/
public interface MemberPackageRelationMapper extends GenericMapper<MemberPackageRelation, Integer> {

    List<MemberPackageRelation> listByMemberCode(String memberCode);

}