package cn.whaley.moretv.member.mapper.member;

import java.util.List;

import cn.whaley.moretv.member.base.mapper.GenericMapper;
import cn.whaley.moretv.member.model.member.MemberUserCp;

/**
* Mapper: MemberUserCpMapper
* Model : MemberUserCp
* Table : member_user_cp
*
* This Mapper generated by MyBatis Generator Extend at 2017-04-10 14:14:25
*/
public interface MemberUserCpMapper extends GenericMapper<MemberUserCp, Integer> {

    List<MemberUserCp> listCpInfoByAccount(Integer accountId);
}