package cn.whaley.moretv.member.api.service.member;

import cn.whaley.moretv.member.base.res.ResultResponse;
import cn.whaley.moretv.member.service.member.BaseMemberService;

/**
* Service: MemberService
* Mapper : MemberMapper
* Model  : Member
*
* This Service generated by MyBatis Generator Extend at 2017-03-30 17:05:25
*/
public interface MemberService extends BaseMemberService {

    /**
     * <p>获取用户会员订购续费列表</p>
     *
     * 查询所有会员，和用户对应的会员状态
     *
     * @param accountId
     * @return
     */
    ResultResponse getAllMemberInfo(Integer accountId);
}