package cn.whaley.moretv.member.api.service.member;

import cn.whaley.moretv.member.api.dto.member.MemberInfoResponse;
import cn.whaley.moretv.member.api.dto.member.MemberStatusResponse;
import cn.whaley.moretv.member.base.dto.response.ResultResponse;
import cn.whaley.moretv.member.service.member.BaseMemberService;

import java.util.List;

/**
* Service: MemberService
* Mapper : MemberMapper
* Model  : Member
*
* This Service generated by MyBatis Generator Extend at 2017-03-30 17:05:25
*/
public interface MemberService extends BaseMemberService {

    /**
     * <p>获取用户会员订购续费列表</p>
     *
     * 查询所有会员，和用户对应的会员状态
     *
     * @param accountId
     * @return
     */
    ResultResponse<List<MemberStatusResponse>> getAllMemberInfo(Integer accountId);

    /**
     * <p>获取当前会员</p>
     *
     * 查询账户有效的会员权益
     * @param accountId
     * @return
     */
    ResultResponse<List<MemberInfoResponse>> getMemberInfo(Integer accountId);

    /**
     * <p>账户是否是有效会员</p>
     *
     * @param accountId
     * @return
     */
    Boolean accountIsMember(Integer accountId);

    /**
     * <p>账户是否为指定的会员</p>
     *
     * @param accountId
     * @param memberCode
     * @return
     */
    Boolean accountIsMember(Integer accountId, String memberCode);


    /**
     * <p>查询账户是否为腾讯会员</p>
     *
     * @param accountId
     * @return
     */
    Boolean accountIsTencentMember(Integer accountId);

}