package cn.whaley.moretv.member.sync.service.member;

import cn.whaley.moretv.member.base.service.GenericService;
import cn.whaley.moretv.member.model.member.Member;

/**
* Service: MemberService
* Mapper : MemberMapper
* Model  : Member
*
* This Service generated by MyBatis Generator Extend at 2017-03-29 14:25:15
*/
public interface MemberService extends GenericService<Member, Integer> {
}