package cn.whaley.moretv.member.sync.service.goods;

import cn.whaley.moretv.member.base.service.GenericService;
import cn.whaley.moretv.member.model.goods.Goods;

/**
* Service: GoodsService
* Mapper : GoodsMapper
* Model  : Goods
*
* This Service generated by MyBatis Generator Extend at 2017-02-20 19:19:11
*/
public interface GoodsService extends GenericService<Goods, Integer> {
}