package cn.whaley.moretv.member.sync.service.goods;

import cn.whaley.moretv.member.base.service.GenericService;
import cn.whaley.moretv.member.model.goods.Member;
import cn.whaley.moretv.member.sync.dto.goods.MemberDto;

/**
* Service: MemberService
* Mapper : MemberMapper
* Model  : Member
*
* This Service generated by MyBatis Generator Extend at 2017-03-02 17:00:35
*/
public interface MemberService extends GenericService<Member, Integer> {

    void sync(MemberDto memberDto);
}