package cn.whaley.moretv.member.sync.service.goods;

import cn.whaley.moretv.member.base.service.GenericService;
import cn.whaley.moretv.member.model.goods.MemberPackageRelation;

/**
* Service: MemberPackageRelationService
* Mapper : MemberPackageRelationMapper
* Model  : MemberPackageRelation
*
* This Service generated by MyBatis Generator Extend at 2017-03-02 17:06:04
*/
public interface MemberPackageRelationService extends GenericService<MemberPackageRelation, Integer> {
}