package cn.whaley.moretv.member.api.service.order.impl;

import cn.whaley.moretv.member.api.service.order.OrderItemService;
import cn.whaley.moretv.member.base.service.impl.GenericServiceImpl;
import cn.whaley.moretv.member.mapper.order.OrderItemMapper;
import cn.whaley.moretv.member.model.order.OrderItem;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
* ServiceImpl: OrderItemServiceImpl
* Mapper : OrderItemMapper
* Model  : OrderItem
*
* This ServiceImpl generated by MyBatis Generator Extend at 2017-04-27 15:33:08
*/
@Service
@Transactional
public class OrderItemServiceImpl extends GenericServiceImpl<OrderItem, Integer, OrderItemMapper> implements OrderItemService {
    @Autowired
    private OrderItemMapper orderItemMapper;

    @Override
    public OrderItemMapper getGenericMapper() {
        return orderItemMapper;
    }
}