package cn.whaley.moretv.member.mapper;

import cn.whaley.moretv.member.base.mapper.GenericMapper;
import cn.whaley.moretv.member.model.DeliveredOrder;

/**
* Mapper: DeliveredOrderMapper
* Model : DeliveredOrder
* Table : delivered_order
*
* This Mapper generated by MyBatis Generator Extend at 2017-04-27 15:27:07
*/
public interface DeliveredOrderMapper extends GenericMapper<DeliveredOrder, Integer> {
}