package cn.whaley.moretv.member.model.goods;

import cn.whaley.moretv.member.base.model.BaseModel;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
* Model: GoodsSku
* Table: goods_sku
* Alias: sku
*
* This Model generated by MyBatis Generator Extend.
*/
public class GoodsSku extends BaseModel<Integer> implements Serializable {
    /**
     * 商品编号
     * goods_code
     */
    private String goodsCode;

    /**
     * 会员编码unit
     * member_code
     */
    private String memberCode;

    /**
     * 月unit
     * duration_month
     */
    private Integer durationMonth;

    /**
     * 日unit
     * duration_day
     */
    private Integer durationDay;

    /**
     * 商品原价
     * original_price
     */
    private Integer originalPrice;

    /**
     * 折扣价
     * discount
     */
    private BigDecimal discount;

    /**
     * 销售价格
     * selling_price
     */
    private Integer sellingPrice;

    /**
     * 创建时间/录入时间
     * create_time
     */
    private Date createTime;

    /**
     * 修改时间
     * update_time
     */
    private Date updateTime;

    private static final long serialVersionUID = 1L;

    /**
     * 商品编号
     * goods_code
     */
    public String getGoodsCode() {
        return goodsCode;
    }

    /**
     * 商品编号
     * goods_code
     *
     * @param goodsCode 商品编号
     */
    public void setGoodsCode(String goodsCode) {
        this.goodsCode = goodsCode;
    }

    /**
     * 会员编码unit
     * member_code
     */
    public String getMemberCode() {
        return memberCode;
    }

    /**
     * 会员编码unit
     * member_code
     *
     * @param memberCode 会员编码unit
     */
    public void setMemberCode(String memberCode) {
        this.memberCode = memberCode;
    }

    /**
     * 月unit
     * duration_month
     */
    public Integer getDurationMonth() {
        return durationMonth;
    }

    /**
     * 月unit
     * duration_month
     *
     * @param durationMonth 月unit
     */
    public void setDurationMonth(Integer durationMonth) {
        this.durationMonth = durationMonth;
    }

    /**
     * 日unit
     * duration_day
     */
    public Integer getDurationDay() {
        return durationDay;
    }

    /**
     * 日unit
     * duration_day
     *
     * @param durationDay 日unit
     */
    public void setDurationDay(Integer durationDay) {
        this.durationDay = durationDay;
    }

    /**
     * 商品原价
     * original_price
     */
    public Integer getOriginalPrice() {
        return originalPrice;
    }

    /**
     * 商品原价
     * original_price
     *
     * @param originalPrice 商品原价
     */
    public void setOriginalPrice(Integer originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * 折扣价
     * discount
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * 折扣价
     * discount
     *
     * @param discount 折扣价
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * 销售价格
     * selling_price
     */
    public Integer getSellingPrice() {
        return sellingPrice;
    }

    /**
     * 销售价格
     * selling_price
     *
     * @param sellingPrice 销售价格
     */
    public void setSellingPrice(Integer sellingPrice) {
        this.sellingPrice = sellingPrice;
    }

    /**
     * 创建时间/录入时间
     * create_time
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 创建时间/录入时间
     * create_time
     *
     * @param createTime 创建时间/录入时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 修改时间
     * update_time
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 修改时间
     * update_time
     *
     * @param updateTime 修改时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", goodsCode=").append(goodsCode);
        sb.append(", memberCode=").append(memberCode);
        sb.append(", durationMonth=").append(durationMonth);
        sb.append(", durationDay=").append(durationDay);
        sb.append(", originalPrice=").append(originalPrice);
        sb.append(", discount=").append(discount);
        sb.append(", sellingPrice=").append(sellingPrice);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GoodsSku other = (GoodsSku) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}