package cn.whaley.moretv.member.model.goods;

import cn.whaley.moretv.member.base.model.BaseModel;
import java.io.Serializable;
import java.util.Date;

/**
* Model: MemberPackageRelation
* Table: member_package_relation
* Alias: mpr
*
* This Model generated by MyBatis Generator Extend.
*/
public class MemberPackageRelation extends BaseModel<Integer> implements Serializable {
    /**
     * 会员模型编码
     * member_code
     */
    private String memberCode;

    /**
     * 会员模型名称
     * member_name
     */
    private String memberName;

    /**
     * 节目包编码
     * package_code
     */
    private String packageCode;

    /**
     * 节目包名称
     * package_name
     */
    private String packageName;

    /**
     * 节目源code
     * program_source_code
     */
    private String programSourceCode;

    /**
     * 节目源显示名称
     * program_source_label
     */
    private String programSourceLabel;

    /**
     * 节目源的源头类型
     * program_source_original_type
     */
    private String programSourceOriginalType;

    /**
     * 节目源外部编码
     * program_source_external_code
     */
    private String programSourceExternalCode;

    /**
     * deleted：删除，unbound：解绑，bound：绑定
     * status
     */
    private String status;

    /**
     * 创建时间
     * create_time
     */
    private Date createTime;

    /**
     * 更新时间
     * update_time
     */
    private Date updateTime;

    private static final long serialVersionUID = 1L;

    /**
     * 会员模型编码
     * member_code
     */
    public String getMemberCode() {
        return memberCode;
    }

    /**
     * 会员模型编码
     * member_code
     *
     * @param memberCode 会员模型编码
     */
    public void setMemberCode(String memberCode) {
        this.memberCode = memberCode;
    }

    /**
     * 会员模型名称
     * member_name
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * 会员模型名称
     * member_name
     *
     * @param memberName 会员模型名称
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName;
    }

    /**
     * 节目包编码
     * package_code
     */
    public String getPackageCode() {
        return packageCode;
    }

    /**
     * 节目包编码
     * package_code
     *
     * @param packageCode 节目包编码
     */
    public void setPackageCode(String packageCode) {
        this.packageCode = packageCode;
    }

    /**
     * 节目包名称
     * package_name
     */
    public String getPackageName() {
        return packageName;
    }

    /**
     * 节目包名称
     * package_name
     *
     * @param packageName 节目包名称
     */
    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    /**
     * 节目源code
     * program_source_code
     */
    public String getProgramSourceCode() {
        return programSourceCode;
    }

    /**
     * 节目源code
     * program_source_code
     *
     * @param programSourceCode 节目源code
     */
    public void setProgramSourceCode(String programSourceCode) {
        this.programSourceCode = programSourceCode;
    }

    /**
     * 节目源显示名称
     * program_source_label
     */
    public String getProgramSourceLabel() {
        return programSourceLabel;
    }

    /**
     * 节目源显示名称
     * program_source_label
     *
     * @param programSourceLabel 节目源显示名称
     */
    public void setProgramSourceLabel(String programSourceLabel) {
        this.programSourceLabel = programSourceLabel;
    }

    /**
     * 节目源的源头类型
     * program_source_original_type
     */
    public String getProgramSourceOriginalType() {
        return programSourceOriginalType;
    }

    /**
     * 节目源的源头类型
     * program_source_original_type
     *
     * @param programSourceOriginalType 节目源的源头类型
     */
    public void setProgramSourceOriginalType(String programSourceOriginalType) {
        this.programSourceOriginalType = programSourceOriginalType;
    }

    /**
     * 节目源外部编码
     * program_source_external_code
     */
    public String getProgramSourceExternalCode() {
        return programSourceExternalCode;
    }

    /**
     * 节目源外部编码
     * program_source_external_code
     *
     * @param programSourceExternalCode 节目源外部编码
     */
    public void setProgramSourceExternalCode(String programSourceExternalCode) {
        this.programSourceExternalCode = programSourceExternalCode;
    }

    /**
     * deleted：删除，unbound：解绑，bound：绑定
     * status
     */
    public String getStatus() {
        return status;
    }

    /**
     * deleted：删除，unbound：解绑，bound：绑定
     * status
     *
     * @param status deleted：删除，unbound：解绑，bound：绑定
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * 创建时间
     * create_time
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 创建时间
     * create_time
     *
     * @param createTime 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 更新时间
     * update_time
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 更新时间
     * update_time
     *
     * @param updateTime 更新时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", memberCode=").append(memberCode);
        sb.append(", memberName=").append(memberName);
        sb.append(", packageCode=").append(packageCode);
        sb.append(", packageName=").append(packageName);
        sb.append(", programSourceCode=").append(programSourceCode);
        sb.append(", programSourceLabel=").append(programSourceLabel);
        sb.append(", programSourceOriginalType=").append(programSourceOriginalType);
        sb.append(", programSourceExternalCode=").append(programSourceExternalCode);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MemberPackageRelation other = (MemberPackageRelation) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}